---
default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [-l 120]
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-print
          - flake8-absolute-import
          - flake8-eradicate
          - flake8-bugbear
          - flake8-pytest
          - flake8-keyword-arguments
          - flake8-docstrings
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.2
    hooks:
      - id: reorder-python-imports
        args:
          - --application-directories=src
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        args: [--show-absolute-path]
        exclude: setup.py
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/pylint
    rev: v2.14.5
    hooks:
      - id: pylint
        name: pylint
        exclude: (\/test_\S*|_test|conftest)\.py$
      - id: pylint
        name: pylint-test
        files: (\/test_\S*|_test|conftest)\.py$
        args:
          - -d duplicate-code
          - -d attribute-defined-outside-init
          - -d too-many-arguments
          - -d too-many-locals
          - -d too-many-public-methods
